Friendship 2
kelibst/ror-social-scaffold pull request #3
Opened 2020-05-30 05:07 UTC by kelibst

- Try to implement friendships with 2 rows for mutual friendship. Remember about unit and integrations tests!

2020-05-30 07:08 UTC, wathigo requested changes
## CHANGES REQUIRED 
Great effort on this project @kelibst 
Let's make some changes in order to make the friendship feature more efficient.

### REQUIRED
* When friendship is confirmed, an additional row with reversed user-friend pair is created.
After accepting a friendship only one row was created as shown :point_down: 
![Screenshot from 2020-05-30 09-55-23](https://user-images.githubusercontent.com/44072711/83321888-d5264480-a25b-11ea-93c2-7f07b76a0062.png)
* The database configurations are not correct. Let's remove user specific configs like username and password.
* We have some failing tests.
![Screenshot from 2020-05-30 10-00-46](https://user-images.githubusercontent.com/44072711/83321954-85944880-a25c-11ea-8ee9-88b309990c9b.png)
* See the comments for more pointer :point_down: 

**After implementing the changes, submit another request for review.**

**Good luck in your next submission :four_leaf_clover: 
Simon Wathigo**

2020-05-30 07:08 UTC, wathigo commented on app/controllers/friendship_controller.rb
> +  end
This method is quit long. Can we split it into several methods, each having a single responsibility. Like we can have `create` method for only creating a friendship record, `destroy` for cancelling a friend request, `update` for accepting a friend request.
You can read more about single responsibility principle [here](https://www.sitepoint.com/solid-ruby-single-responsibility-principle/)

2020-06-01 13:06 UTC, uryelah commented
Hello **Keli Dogbevi**, I'm Sarah your last reviewer for this PR 👩‍🚀 

Great job, you did  some hardcore refactoring on the req_init method!
The inverse friendships look to be working too.

-------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**


---------

    
    
**Keep being an awesome dev and good luck with your next project!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-06-01 13:36 UTC, kelibst commented
Thanks Sarah

> Hello **Keli Dogbevi**, I'm Sarah your last reviewer for this PR 
> 
> Great job, you did some hardcore refactoring on the req_init method!
> The inverse friendships look to be working too.
> 
> ## **Your project is approved! confetti_ball goal_net yellow_heart**
> **You may close this Pull Request and merge the changes**
> 
> **Keep being an awesome dev and good luck with your next project!**
> 
> Cheers and Happy coding!
> 
> Code review by **Sarah Uryelah Silva Chamorro**
> 
> (Feel free to contact me on slack by the handle of **sarah** if you have any additional question)

2020-06-01 13:36 UTC, merged