Deploy app
kelibst/ror-social-scaffold pull request #4
Opened 2020-06-01 13:37 UTC by kelibst

Deployed to Heroku

2020-06-01 16:51 UTC, whiz25 requested changes
## Nice Try
I was not able to see how your app works because the live link doesn't work. Please make the following changes.
- [ ] The live link points to the odin project page. Fix that
- [ ] Make your Readme more professional. Check my comments


### Martin Afani

2020-06-01 16:52 UTC, whiz25 commented on README.md
> +# ([Live link](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
- fix this link

2020-06-01 16:54 UTC, whiz25 commented on README.md
> +## Live link
- What does TBA mean? Is it an instruction for deploying the app to heroku? Please give us precise details on how one can deploy this app to heroku

2020-06-01 18:32 UTC, whiz25 approved these changes
## Congratulations :clap:
You made the required changes and its therefore a :+1: from me. Merge and proceed.

### Martin Afani

2020-06-01 18:42 UTC, whiz25 approved these changes
## Hey @kelibst 
You have made the required changes for this milestone. I must admit making a mistake in approving milestone 7 of this project. It's in that milestone that you are supposed to enable signup using facebook. 
Please add that feature as well. Meanwhile, I will approve this PR since it meets the minimum requirements.

### Martin Afani

2020-06-02 07:03 UTC, kelibst commented
Thanks guys

2020-06-02 07:03 UTC, merged